export interface WilayaData {
  code: string;
  name: string;
  dairas: string[];
}

export const WILAYAS: WilayaData[] = [
  { code: "01", name: "Adrar", dairas: ["Adrar","Reggane","Aoulef","Timimoun","In Salah","Bordj Badji Mokhtar","Tsabit","Fenoughil","Charouine","Zaouiet Kounta","Tit"] },
  { code: "02", name: "Chlef", dairas: ["Chlef","Ténès","El Karimia","Boukadir","Oued Fodda","Ain Merane","Ouled Ben Abdelkader","Zeboudja","Abou El Hassan","Oued Sly","Taougrit","El Marsa","Beni Haoua"] },
  { code: "03", name: "Laghouat", dairas: ["Laghouat","Aflou","Ksar El Hirane","Hassi R'Mel","Brida","Oued Morra","El Ghicha","Ain Madhi","Gueltat Sidi Saad","Had Sahary"] },
  { code: "04", name: "Oum El Bouaghi", dairas: ["Oum El Bouaghi","Ain Beida","Ain M'Lila","Ksar Sbahi","Meskiana","Ain Fakroun","Sigus","Dhalaa","Souk Naâmane","Ain Babouche","F'Kirina","Ain Kercha"] },
  { code: "05", name: "Batna", dairas: ["Batna","Barika","N'Gaous","Ain Touta","Merouana","Tazoult","Arris","Menaa","Ras El Aioun","Ain Djasser","Seggana","Timgad","El Madher","Chemora","Tkout","Ichemoul"] },
  { code: "06", name: "Béjaïa", dairas: ["Béjaïa","Akbou","Sidi Aich","Amizour","El Kseur","Tichy","Kherrata","Seddouk","Adekar","Barbacha","Darguina","Aokas","Chemini","Souk El Ténine","Tazmalt"] },
  { code: "07", name: "Biskra", dairas: ["Biskra","Sidi Okba","Tolga","Ouled Djellal","M'Chounèche","El Kantara","Djamorah","Zeribet El Oued","Foughala","Sidi Khaled","Ourlal","El Outaya"] },
  { code: "08", name: "Béchar", dairas: ["Béchar","Kenadsa","Abadla","Beni Ounif","Taghit","Beni Abbes","Igli","Lahmar","Tabelbala","El Ouata","Mechraa Houari"] },
  { code: "09", name: "Blida", dairas: ["Blida","Boufarik","Bougara","Mouzaia","Oued El Alleug","Larbaa","El Affroun","Bouinan","Beni Mered","Ain Romana"] },
  { code: "10", name: "Bouira", dairas: ["Bouira","Lakhdaria","Sour El Ghozlane","M'Chedallah","Ain Bessem","Bordj Okhriss","Haizer","Bechloul","El Hachimia","Kadiria","Bir Ghbalou","Aghbalou"] },
  { code: "11", name: "Tamanrasset", dairas: ["Tamanrasset","In Guezzam","In Salah","Abalessa","Silet","Tazrouk","Ideles","In Amguel"] },
  { code: "12", name: "Tébessa", dairas: ["Tébessa","Bir El Ater","Chéria","El Aouinet","Morsott","Ouenza","El Ogla","El Ma Labiod","Negrine","Bouchegouf","Hammamet","El Kouif"] },
  { code: "13", name: "Tlemcen", dairas: ["Tlemcen","Maghnia","Ghazaouet","Remchi","Nedroma","Sebdou","Hennaya","Bab El Assa","Beni Snous","Mansourah","Chetouane","Sidi Djillali","Honaine","Ouled Mimoun","Fellaoucène"] },
  { code: "14", name: "Tiaret", dairas: ["Tiaret","Frenda","Sougueur","Ksar Chellala","Mahdia","Dahmouni","Ain Deheb","Rahouia","Mechraa Sfa","Oued Lilli","Meghila","Hammadia","Ain Kermes","Medroussa"] },
  { code: "15", name: "Tizi Ouzou", dairas: ["Tizi Ouzou","Ain El Hammam","Azzefoun","Beni Douala","Bouzeguene","Boghni","Draa Ben Khedda","Draa El Mizan","Iferhounene","Irdjen","Larbaa Nath Irathen","Maatkas","Makouda","Mekla","Ouacifs","Ouadhias","Ouaguenoun","Tigzirt","Azeffoun"] },
  { code: "16", name: "Alger", dairas: ["Bab El Oued","Sidi M'Hamed","Hussein Dey","El Harrach","Baraki","Bab Ezzouar","Bir Mourad Rais","Bouzareah","Cheraga","Dar El Beida","Draria","Zeralda","Birtouta"] },
  { code: "17", name: "Djelfa", dairas: ["Djelfa","Messaad","Ain Oussera","Hassi Bahbah","Dar Chioukh","Charef","Sidi Laadjel","Birine","Moudjebara","Had Sahary","Ain El Ibel","Faidh El Botma"] },
  { code: "18", name: "Jijel", dairas: ["Jijel","El Milia","Taher","Chekfa","Sidi Maârouf","Ziama Mansouriah","Settara","El Ancer","Texenna","Djimla","El Aouana"] },
  { code: "19", name: "Sétif", dairas: ["Sétif","El Eulma","Ain Oulmene","Bougaa","Ain El Kebira","Ain Arnat","Ain Azel","Beni Aziz","Beni Ourtilane","Bouandas","Guenzet","Hammam Guergour","Hammam Soukhna","Ksar El Abtal","Maoklane","Salah Bay"] },
  { code: "20", name: "Saïda", dairas: ["Saïda","Ain El Hadjar","Hassasna","Youb","Ouled Brahim","Sidi Boubekeur"] },
  { code: "21", name: "Skikda", dairas: ["Skikda","Azzaba","Collo","El Harrouch","Tamalous","Ain Bouziane","Sidi Mezghiche","Zitouna","Ramdane Djamel","Oum Toub","Ben Azzouz","El Hadaiek","Oued Zhour"] },
  { code: "22", name: "Sidi Bel Abbès", dairas: ["Sidi Bel Abbès","Telagh","Ain El Berd","Sfissef","Ben Badis","Ras El Ma","Sidi Ali Benyoub","Marhoum","Moulay Slissen","Tessala","Merine","Mostefa Ben Brahim"] },
  { code: "23", name: "Annaba", dairas: ["Annaba","El Bouni","El Hadjar","Ain El Berda","Berrahal","Chetaibi"] },
  { code: "24", name: "Guelma", dairas: ["Guelma","Bouchegouf","Oued Zenati","Héliopolis","Hammam Debagh","Ain Makhlouf","Khezaras","Ain Ben Beida","Guelaat Bou Sbaa","Hammam N'Bails"] },
  { code: "25", name: "Constantine", dairas: ["Constantine","El Khroub","Ain Smara","Zighoud Youcef","Hamma Bouziane","Ibn Ziad"] },
  { code: "26", name: "Médéa", dairas: ["Médéa","Berrouaghia","Ksar El Boukhari","Tablat","Beni Slimane","El Omaria","Ain Boucif","Si Mahdjoub","Chahbounia","Ouled Antar","Aziz","Seghouane","Ouamri"] },
  { code: "27", name: "Mostaganem", dairas: ["Mostaganem","Ain Tedeles","Sidi Ali","Achaacha","Hassi Mamèche","Ain Nouissy","Mesra","Bouguirat","Sidi Lakhdar"] },
  { code: "28", name: "M'Sila", dairas: ["M'Sila","Bou Saada","Sidi Aissa","Ain El Melh","Hammam Dalaa","Magra","Khoubana","Djebel Messaad","Ouled Derradj","Ben Srour","Medjedel","Ain El Hadjel","Ouled Sidi Brahim"] },
  { code: "29", name: "Mascara", dairas: ["Mascara","Sig","Tighennif","Mohammadia","Ain Fares","Ghriss","Bouhanifia","Hachem","Oggaz","El Bordj","Oued El Abtal","Oued Taria"] },
  { code: "30", name: "Ouargla", dairas: ["Ouargla","Touggourt","Hassi Messaoud","El Hadjira","Temacine","Taibet","Megarine","N'Goussa","Sidi Khouiled","El Borma"] },
  { code: "31", name: "Oran", dairas: ["Oran","Es Senia","Ain El Turk","Bir El Djir","Arzew","Bethioua","Boutlelis","Gdyel","Oued Tlelat"] },
  { code: "32", name: "El Bayadh", dairas: ["El Bayadh","Bougtob","Brezina","Labiodh Sidi Cheikh","Ain El Orak","Boussemghoun","El Abiodh Sidi Cheikh","Chellala","Stidia"] },
  { code: "33", name: "Illizi", dairas: ["Illizi","Djanet","In Amenas","Bordj El Houasse","Debdeb"] },
  { code: "34", name: "Bordj Bou Arréridj", dairas: ["Bordj Bou Arréridj","Ras El Oued","Bir Kasd Ali","El Achir","Mansourah","Medjana","Bordj Ghedir","Bordj Zemoura","Djaafra","Ain Taghrout"] },
  { code: "35", name: "Boumerdès", dairas: ["Boumerdès","Dellys","Baghlia","Bordj Menaiel","Boudouaou","Isser","Khemis El Khechna","Naciria","Ouled Moussa"] },
  { code: "36", name: "El Tarf", dairas: ["El Tarf","El Kala","Bouhadjar","Ben M'Hidi","Bouchegouf","Ain El Assel","Besbes","Dréan"] },
  { code: "37", name: "Tindouf", dairas: ["Tindouf","Oum El Assel"] },
  { code: "38", name: "Tissemsilt", dairas: ["Tissemsilt","Bordj Bou Naâma","Theniet El Had","Lardjem","Ammari","Layoune","Khemisti","Ouled Bessam"] },
  { code: "39", name: "El Oued", dairas: ["El Oued","Djamaa","Guemar","Robbah","Bayadha","El Meghaier","Hassi Khelifa","Oued El Alenda","Still","Debila","Taleb Larbi","Magrane"] },
  { code: "40", name: "Khenchela", dairas: ["Khenchela","Kais","Ain Touila","Bouhmama","El Hamma","Chechar","Ouled Rechache","Babar"] },
  { code: "41", name: "Souk Ahras", dairas: ["Souk Ahras","Sedrata","M'Daourouch","Hanancha","Bir Bouhouche","Ouled Driss","Taoura","Ain Zana","Ouillen","Merahna"] },
  { code: "42", name: "Tipaza", dairas: ["Tipaza","Cherchell","Koléa","Hadjout","Bou Ismail","Gouraya","Damous","Ahmer El Ain","Fouka","Sidi Amar"] },
  { code: "43", name: "Mila", dairas: ["Mila","Chelghoum Laid","Ferdjioua","Ain Tine","Grarem Gouga","Oued Endja","Tassadane Haddada","Rouached","Terrai Bainen","Sidi Merouane","Oued Athmania","Teleghma","Ain Beida Harriche"] },
  { code: "44", name: "Aïn Defla", dairas: ["Aïn Defla","Miliana","Khemis Miliana","Djelida","El Attaf","Hammam Righa","El Abadia","Ain Lechiakh","Boumedfaa","Djendel","Bathia","Rouina"] },
  { code: "45", name: "Naâma", dairas: ["Naâma","Mecheria","Ain Sefra","Tiout","Moghrar","Sfissifa","Asla"] },
  { code: "46", name: "Aïn Témouchent", dairas: ["Aïn Témouchent","El Malah","Beni Saf","Hammam Bou Hadjar","El Amria","Ain El Arbaa","Oulhaca","Ain Kihal"] },
  { code: "47", name: "Ghardaïa", dairas: ["Ghardaïa","Metlili","El Meniaa","Berriane","Guerrara","Daïa Ben Dahoua","Zelfana","Bounoura","El Atteuf","Mansourah"] },
  { code: "48", name: "Relizane", dairas: ["Relizane","Oued Rhiou","Mazouna","Mendes","Ain Tarek","Zemmora","Yellel","Ammi Moussa","Ramka","El Matmar","Djidioua","Sidi M'Hamed Ben Ali"] },
  { code: "49", name: "El M'Ghair", dairas: ["El M'Ghair","Djamaa","Oum Touyour","Sidi Khaled","Still"] },
  { code: "50", name: "El Meniaa", dairas: ["El Meniaa","Hassi Gara"] },
  { code: "51", name: "Ouled Djellal", dairas: ["Ouled Djellal","Sidi Khaled","Doucen","Chaiba"] },
  { code: "52", name: "Bordj Badji Mokhtar", dairas: ["Bordj Badji Mokhtar","Timiaouine"] },
  { code: "53", name: "Béni Abbès", dairas: ["Béni Abbès","Igli","Tabelbala","El Ouata","Kerzaz"] },
  { code: "54", name: "Timimoun", dairas: ["Timimoun","Charouine","Ouled Said","Adrar","Aougrout","Tinerkouk"] },
  { code: "55", name: "Touggourt", dairas: ["Touggourt","Temacine","Megarine","Taibet","El Hadjira"] },
  { code: "56", name: "Djanet", dairas: ["Djanet","Bordj El Houasse"] },
  { code: "57", name: "In Salah", dairas: ["In Salah","In Ghar","Foggaret Ezzaouia"] },
  { code: "58", name: "In Guezzam", dairas: ["In Guezzam","Tin Zaouatine"] },
];

export function getWilayaLabel(w: WilayaData): string {
  return `${w.code} - ${w.name}`;
}
